os:
  - linux

language:
  - java

install:
  - ant deps

jdk:
  - oraclejdk8
  # - openjdk8
  # - oraclejdk9
  # - openjdk10
  # - openjdk11
  # - oraclejdk11

script:
  - ant clean
  - ant compile
  - ant jar
  - ant run
