name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
        distribution: ['temurin']
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Compile with Ant
        run: ant -Dplatforms.JDK_${{ matrix.java }}.home=${JAVA_HOME} compile
      - name: Build with Ant
        run: ant -Dplatforms.JDK_${{ matrix.java }}.home=${JAVA_HOME} jar
      - name: Run with Ant
        run: ant run
